/*
변수 설명
  proprocessor: 전처리문의 개수
  octal number: 8진법 숫자의 개수
  negative decimal number: 10진법 음수의 개수
  positive decimal number: 10진법 양수의 개수
  
  operator: 산술/논리/관계/증감/콤마/참조/포인터 연산자의 개수
  comment: 주석문의 개수 (//, /**/ 주석문 안 값은 count 안 됨)
  
  '=': =기호의 개수
  '{': {기호의 개수
  '}': }기호의 개수
  
  wordcase1: p가 두번만 들어간 단어의 개수( ex> pp, pop, ...)
  wordcase2: e로 시작하고 m으로 끝나는 단어의 개수
  word: 그 외 단어의 개수
  
  mark: 위에서 count되지 않은 문자의 개수
  
  
*/
